name: BMAD Method
description: Scale-adaptive agile AI-driven development framework with creative intelligence and game development extensions.
version: 1.0.0
settings_sections: []
per_project_config: true
per_agent_config: false
